services:
  - type: web
    name: asesoria-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd src && export PYTHONPATH=$PYTHONPATH:$(pwd) && gunicorn app.app:app --config gunicorn.conf.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: SECRET_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: AZURE_STORAGE_ACCOUNT_NAME
        sync: false
      - key: AZURE_STORAGE_ACCOUNT_KEY
        sync: false
      - key: AZURE_CLIENTE_ACCOUNT_KEY
        sync: false
      - key: AZURE_CONTAINER_NAME
        sync: false
      - key: AZURE_CLIENTE_CONTAINER
        sync: false
      - key: AZURE_SPEECH_KEY
        sync: false
      - key: AZURE_SPEECH_REGION
        sync: false
      - key: API_KEY
        sync: false 