services:
  - type: web
    name: verano
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd src && gunicorn --config gunicorn.conf.py main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        sync: false
      - key: AZURE_STORAGE_ACCOUNT_NAME
        sync: false
      - key: AZURE_STORAGE_ACCOUNT_KEY
        sync: false
      - key: AZURE_CONTAINER_NAME
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_PROJECT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false
    healthCheckPath: /health
    autoDeploy: true
    plan: free
    timeout: 300  # 5 minutos de timeout 