services:
  - type: web
    name: analizador-presentaciones
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: TRANSCRIBER_PROVIDER
        value: azure
      - key: AZURE_SPEECH_KEY
        sync: false
      - key: AZURE_SPEECH_REGION
        sync: false
      - key: AZURE_STORAGE_ACCOUNT_NAME
        sync: false
      - key: AZURE_STORAGE_ACCOUNT_KEY
        sync: false
      - key: AZURE_CONTAINER_NAME
        value: archivos-miapp-kiko
    healthCheckPath: /health
    autoDeploy: true 