services:
  - type: web
    name: analizador-presentaciones
    env: python
    buildCommand: pip install -r src/config/requirements.txt
    startCommand: gunicorn --config src/config/gunicorn.conf.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: AZURE_STORAGE_ACCOUNT_NAME
        sync: false
      - key: AZURE_STORAGE_ACCOUNT_KEY
        sync: false
      - key: AZURE_SPEECH_KEY
        sync: false
      - key: AZURE_SPEECH_REGION
        sync: false
      - key: AZURE_CONTAINER_NAME
        sync: false
    healthCheckPath: /health
    autoDeploy: true
    plan: free
    timeout: 300  # 5 minutos de timeout 